version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      # - ./database-dump.sql:/docker-entrypoint-initdb.d/database-dump.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres